cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('liq/checkout', views.cart_detail_liqour, name='cart_detail_liq'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delivery/', views.DeliveryDetails.as_view(), name='cart_delivery'),
    path('liq/delivery/', views.DeliveryDetailsLiqour.as_view(), name='cart_delivery_liq'),
]

menus/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path('test/', views.ViewTest.as_view(), name='test'),
    path('upload_menu/', views.menu_upload, name='upload'),
    path('upload_size/', views.size_upload, name='upload-size'),
    path('upload_add_ons/', views.add_ons_upload, name='upload-add_ons'),
    path('price/<int:item_id>', views.item_prices_get, name='price'),
    path('adds_on/<int:item_id>', views.get_adds_on, name='adds-on'),
    path('same_item/<int:item_id>', views.same_items_in_cart, name='same-item'),
    path('order/<int:item_id>', views.item_to_order, name='order'),
    path('list/<str:city>/', views.MenuList.as_view(), name='list'),
    path('create/', views.MenuCreate.as_view(), name='create'),
    path('item_create/', views.ItemCreate.as_view(), name='item-create'),
    path('item_update/<int:pk>', views.ItemUpdate.as_view(), name='item-update'),
    path('item_delete/<int:pk>', views.ItemDelete.as_view(), name='item-delete'),
    path('get_category_items/<int:cat_id>', views.get_category_items, name='get-items'),
    path('category_create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category_update/<int:pk>', views.CategoryUpdate.as_view(), name='category-update'),
    path('category_delete/<int:pk>', views.CategoryDelete.as_view(), name='category-delete'),
    path('ad_update/<int:pk>', views.AdUpdate.as_view(), name='ad-update'),
    path('count_visit/', views.menu_access_count, name='count'),
    path('establishment_create/', views.EstablishmentCreate.as_view(), name='establishment-create'),
    path('<slug:title_slug>/editar/', views.MenuEditDetails.as_view(), name='edit'),
    path('<slug:title_slug>/edit/<int:partial>', views.MenuEditDetails.as_view(), name='edit-partial'),
    path('<slug:title_slug>/', views.MenuDetails.as_view(), name='details'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('', include('index.urls', namespace="index")),
    path('account/', include('account.urls', namespace='account')),
    path('menu/', include('menus.urls', namespace='menu')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menus/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.utils.translation import gettext as _

from menus.helpers.choices import SIZES, NONE, TEMPLATES, SLIDES


class Menu(models.Model):
    """ Database model for menus"""
    owner = models.ForeignKey(get_user_model(),
                              on_delete=models.CASCADE,
                              related_name='menus',
                              verbose_name=_('owner')
                              )
    establishment = models.ForeignKey('Establishment',
                                      on_delete=models.SET_NULL,
                                      null=True,
                                      related_name='establishments',
                                      verbose_name=_('establishment')
                                      )
    title = models.CharField(_('title'), max_length=40, unique=True)
    title_slug = models.SlugField(unique=True)
    subtitle = models.CharField(_('subtitle'), max_length=50)
    description = models.TextField(_('description'), max_length=500)
    logo = models.ImageField(_('logo'), default="images/default/no_photo.png")
    template = models.CharField(max_length=30, choices=TEMPLATES, default=NONE)
    city = models.CharField(max_length=127, null=True, blank=True)
    address = models.CharField(max_length=127, null=True, blank=True)
    lat = models.FloatField(default=0.0)
    lng = models.FloatField(default=0.0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.title_slug:
            self.title_slug = slugify(self.title)
        super(Menu, self).save(*args, **kwargs)


class MenuAnalytic(models.Model):
    """Database model for menu analytics"""
    menu = models.ForeignKey('Menu',
                             on_delete=models.CASCADE,
                             verbose_name=_('menu'),
                             related_name='analytics'
                             )
    visit = models.PositiveIntegerField(_('visits'), default=0)

    def __str__(self):
        return f'Analytics for {self.menu}'


class MenuAdvertising(models.Model):
    menu = models.ForeignKey('Menu',
                             on_delete=models.CASCADE,
                             verbose_name=_('menu'),
                             related_name='ads'
                             )
    photo = models.ImageField(_('photo'), default="images/default/no_photo.png")
    title = models.CharField(_('title'), max_length=30, null=True, blank=True)
    description = models.CharField(_('description'), max_length=60, null=True, blank=True)

    def __str__(self):
        return f'Ad for {self.menu}'

class Item(models.Model):
    """Database model for items"""
    menu = models.ForeignKey('Menu',
                             on_delete=models.CASCADE,
                             verbose_name=_('menu'),
                             related_name='items'
                             )
    category = models.ForeignKey('Category',
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 verbose_name=_('category')
                                 )
    name = models.CharField(_('name'), max_length=30)
    ingredients = models.CharField(_('ingredients'), max_length=511, blank=True)
    notes = models.CharField(_('notes'), max_length=255, null=True, blank=True)
    photo = models.ImageField(_('photo'), default="images/default/no_photo.png")
    upload_code = models.PositiveIntegerField(_('upload code'), default=0, null=True)

    def __str__(self):
        return f'{self.name}-{self.menu}'


class Establishment(models.Model):
    """Database model for Establishments"""
    type = models.CharField(_('type'), max_length=30)

    def __str__(self):
        return self.type


class Category(models.Model):
    """Database model for Category"""
    owner = models.ForeignKey(get_user_model(),
                              on_delete=models.CASCADE,
                              related_name='categories',
                              verbose_name=_('owner')
                              )
    menu = models.ForeignKey("Menu",
                              on_delete=models.CASCADE,
                              related_name='categories',
                              verbose_name=_('Menu'),
                              null=True
                              )
    name = models.CharField(_('name'), max_length=30)
    position = models.PositiveSmallIntegerField(_('position'), )

    class Meta:
        ordering = ['menu', 'position']

    def __str__(self):
        return f'{self.name}, {str(self.menu)}'


class Price(models.Model):
    """Database for size"""
    item = models.ForeignKey('Item', on_delete=models.CASCADE, related_name='prices')
    price = models.DecimalField(_('price_num'), decimal_places=0, max_digits=6)
    price_str = models.CharField(_('price'), max_length=10)
    size = models.CharField(max_length=20, choices=SIZES, default=NONE)
    choice = models.BooleanField(default=False)
    half = models.BooleanField(default=False)

    class Meta:
        ordering = ['item']

    def __str__(self):
        return f'{self.item.menu}: {self.item}, {self.size}'


class ProductInCart(models.Model):
    price = models.ForeignKey('Price', on_delete=models.CASCADE, related_name='inCart')
    total = models.DecimalField(decimal_places=0, max_digits=6, null=True)
    add_on = models.ManyToManyField('AddsOn', through='Quantity')

    def __str__(self):
        return str(self.total)


class AddsOn(models.Model):
    product = models.ManyToManyField('Price', related_name='adds_ons')
    name = models.CharField(max_length=20)
    price = models.DecimalField(_('price_num'), decimal_places=0, max_digits=6)
    price_str = models.CharField(_('price'), max_length=10)

    def __str__(self):
        return self.name


class Quantity(models.Model):
    product = models.ForeignKey('ProductInCart', on_delete=models.CASCADE)
    addOn = models.ForeignKey('AddsOn', on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    price = models.DecimalField(decimal_places=0, max_digits=6, null=True)

    def save(self, *args, **kwargs):
        self.price = self.quantity * self.addOn.price
        super(Quantity, self).save(*args, **kwargs)

menus/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from menus.models import Menu, Item, Category, Establishment, Price, MenuAdvertising

from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext


class MenuForm(forms.ModelForm):
    """Form for creating and editing menu"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = "form-control"
        self.fields['description'].widget.attrs.update(rows='4')

    class Meta:
        model = Menu
        fields = ['owner', 'establishment', 'title', 'subtitle', 'description', 'logo']


class AdForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = "form-control"

    class Meta:
        model = MenuAdvertising
        fields = ['title', 'description', 'photo']


class ItemForm(forms.ModelForm):
    """Form for creating and editing item"""

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop('owner')
        menu = kwargs.pop('menu')
        category = kwargs.pop('category')
        super().__init__(*args, **kwargs)
        if category:
            self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.filter(id=category.id),
                                                             empty_label=None)
            self.fields['category'].widget.attrs['readonly'] = True
        else:
            self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.filter(owner=owner))
            self.fields['category'].empty_label = gettext('Select category')
        if menu:
            self.fields['menu'] = forms.ModelChoiceField(queryset=Menu.objects.filter(id=menu.id),
                                                             empty_label=None)
            self.fields['menu'].widget.attrs['readonly'] = True
        else:
            self.fields['menu'] = forms.ModelChoiceField(queryset=Menu.objects.filter(owner=owner))
            self.fields['menu'].empty_label = gettext('Select menu')
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = "form-control"

        self.fields['category'].initial = category
        self.fields['category'].label = _('category')
        self.fields['photo'].widget.attrs['class'] = "custom-file-input"
        self.fields['menu'].initial = menu
        self.fields['name'].label = _('name')
        self.fields['ingredients'].widget.attrs['placeholder'] = gettext('optional')
        self.fields['ingredients'].label = _('description')
        self.fields['notes'].widget.attrs['placeholder'] = gettext('informacion extra. optional')
        self.fields['notes'].label = _('notas')
        self.fields['ingredients'].required = False
        self.fields['notes'].required = False

    class Meta:
        model = Item
        fields = ['menu', 'category', 'name',
                  'ingredients', 'notes', 'photo',
                  ]


class CategoryForm(forms.ModelForm):
    """Form for creating and editing category"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = "form-control"
        self.fields['name'].label = _('name')

    class Meta:
        model = Category
        fields = ['name', 'position']


class EstablishmentForm(forms.ModelForm):
    """Form for creating and editing category"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = "form-control"

    class Meta:
        model = Establishment
        fields = ['type', ]


class PriceForm(forms.ModelForm):
    """Form for creating price """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['size'].label = _('size')
        self.fields['price_str'].label = _('price')
        self.fields['price_str'].required = True
        self.fields['price_str'].widget.attrs['class'] = "form-control input-price"
        self.fields['size'].widget.attrs['class'] = "form-control input-price"
    price = forms.DecimalField(widget=forms.HiddenInput)

    class Meta:
        model = Price
        fields = ['price', 'price_str', 'size']


ItemPriceFormSet = inlineformset_factory(Item,
                                         Price,
                                         form=PriceForm,
                                         extra=1
                                         )

ItemPriceFormSet2 = inlineformset_factory(Item,
                                          Price,
                                          form=PriceForm,
                                          extra=0,
                                          can_delete=True,
                                          )

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(-1, 21)]


class CartAddProduct(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Cantidad')
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


class MenuUploadForm(forms.Form):
    csv_file = forms.FileField(label=_('csv file'))


class SizeUploadForm(forms.Form):
    csv_file = forms.FileField(label=_('csv file'))

menus/templates/chunks/ad_crud.html
{% load i18n %}
{% load static %}
<div class="row m-3">
    <h4>Editar publicidad</h4>
    <div class="col-12">
        <form method="post" id="formAd" enctype="multipart/form-data">
            {{form}}
        </form>
    </div>
    <div class="col-12 pt-3">
        <button class="btn btn-block btn-primary" onclick="editAd({{id}}, 'post')"> {% trans 'Save' %} </button>
    </div>
</div>

menus/templates/chunks/carousel_ads.html
<div id="carouselAds" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
          {% if ads %}
          {% for ad in ads %}
            <div class="carousel-item {% if forloop.first == 1 %} active {% endif %}" style="min-height:120px;">
              <img class="d-block w-100 py-1" src="{{ad.photo.url}}" alt="">
                {% if ad.title %}
                <div class="carousel-caption py-1 py-md-3" style="background-color: rgba(20, 20, 20, 0.4); left:10%; right:10%;">
                    <h5>{{ad.title}}</h5>
                    <p class="m-0">{{ad.description}}</p>
                </div>
                {% endif %}
                {% if 'edit' in request.path or 'ad_update' in request.path %}
                <div class="position-absolute align-content-center w-100" style="top:5%; left:80%; z-index:100;" onclick="editAd({{ad.id}}, 'get')">
                    <button class="btn btn-secondary">Editar</button>
                </div>
                {% endif %}
            </div>
          {% endfor %}
          {% else %}
           <div class="carousel-item active">
              <img class="d-block w-100 py-1" src="https://digimenu-bucket.s3.amazonaws.com/media/images/default/no_photo.png" alt="image">
            </div>
          {% endif %}
      </div>
      <a class="carousel-control-prev" href="#carouselAds" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselAds" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
</div>

menus/templates/chunks/category_create.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Category' %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-6">
        <form method="post" action="{% url 'menu:category-update' id %}">{% csrf_token %}
            {{form}}
        <button class="btn btn-block btn-primary" type="submit"> {% trans 'Save' %} </button>
    </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

menus/templates/chunks/category_crud.html
{% load i18n %}
{% load static %}
<div class="row m-3">
    {% if 'category_create' in  request.path %}<h4>Crear Categoria</h4>{% else %}<h4>Editar Categoria</h4>{% endif %}
    <div class="col-12">
        <form method="post" id="formCat" action="{% if 'category_create' in  request.path %}{% url 'menu:category-create'%}
        {% else %}{% url 'menu:category-update' id %}{% endif %}">{% csrf_token %}
            {{form}}
        </form>
    </div>
    <div class="col-12 pt-3">
        <button class="btn btn-block btn-primary" onclick="{% if 'category_create' in  request.path %}createCategory('post')
        {% else %}editCategory({{id}}, 'post'){% endif %}"> {% trans 'Save' %} </button>
    </div>
</div>

menus/templates/chunks/item_create.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Item' %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
<form  method="post" enctype=multipart/form-data>{% csrf_token %}
    <div class="row border rounded my-3">
        <div class="col-6">
            <div class="my-3 px-3 bg-light border rounded">
            <div class="row m-1">
                <p class="lead">{% trans 'New product' %}</p>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-primary text-light">{{form.name.label}}</span>
                </div>
                {{form.name}}
            </div>
            <div class="row">
                <div class="col-9 input-group mb-3">
                  <div class="input-group-prepend">
                      <span class="input-group-text bg-primary text-light">{{form.menu.label}}</span>
                  </div>
                    {{form.menu}}
                </div>
                <span>
                    <a href="{% url 'menu:create' %}" class="btn btn-block btn-secondary text-primary" title="{% trans 'add new menu' %}">
                        <i class="fas fa-plus"></i> New Menu
                    </a>
                </span>
                <div class="col-3 pl-0">

                </div>
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                  <span class="input-group-text bg-primary text-light">{{form.category.label}}</span>
              </div>
                {{form.category}}
            </div>
            <div>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-primary text-light">{{form.ingredients.label}}</span>
                </div>
                {{form.ingredients}}
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-primary text-light">{{form.notes.label}}</span>
                </div>
                {{form.notes}}
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text bg-primary text-light" id="inputGroupFileAddon01">{{form.photo.label}}</span>
              </div>
              <div class="custom-file">
                    {{form.photo}}
                <label class="custom-file-label" for="id_photo">{% trans 'choose photo' %}</label>
              </div>
            </div>
            </div>
        </div>
        <div class="col-6">
            <div class="my-3 px-3 bg-light border rounded" id="idPrices">
                <div class="row m-1">
                    <p class="lead">{% trans 'Sizes' %}</p>
                </div>
            {{ price.management_form }}
                {% for form in price %}
                    <div class="row price-row border rounded bg-white p-3 m-1">
                        {{form.id}}
                        {{form.DELETE}}
                        <div class="col-12 input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-primary text-light">{{form.size.label}}</span>
                            </div>
                            {{form.size}}
                        </div>
                        <div class="col-12 input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text bg-primary text-light">{{form.price_str.label}}</span>
                          </div>
                            {{form.price}}
                            {{form.price_str}}
                        </div>
                        <div class="row col-12 buttons">
                             {% if 'item_create' in  request.path %}
                                <div class="col-6">
                                    <button type="button" class="btn btn-block btn-primary text-white add-form-row">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            {% else %}
                                 <div class="col-6">
                                     {% if forloop.last %}
                                        <button type="button" class="btn btn-block btn-primary text-white add-form-row">
                                            <i class="fas fa-plus"></i>
                                        </button>
                                     {% endif %}
                                </div>
                                 <div class="col-6">
                                    <button type="button" class="btn btn-block btn-outline-danger remove-form-row">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>

                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
        </div>
        </div>
        <div class="col-12 my-2">
        <div class="col-4 offset-4">
            <button class="btn btn-block btn-primary" type="submit">{% trans 'SAVE' %}</button>
        </div>
    </div>
    </div>

</form>
{% endblock %}

{% block scripts %}
<script type='text/javascript'>
$(document).ready(function() {
    function updateFieldIndex(el, prefix, index) {
        let id_regex = new RegExp('(' + prefix + '-\\d+)');
        let replacement = prefix + '-' + index

        if ($(el).attr("for")){
            $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        }
        if(el.id) el.id = el.id.replace(id_regex, replacement);
        if(el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function addMore(selector, prefix) {
        let newEl = $(selector).clone(true);
        let total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newEl.show();
        newEl.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each( function(){
            let name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + (total) + '-');
            let id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            $(this).prop('checked', false)
        });
        newEl.find('label').each(function () {
            let forVal = $(this).attr('for');
            if (forVal) {
                forVal = forVal.replace('-' + (total-1) + '-', '-' + total + '-');
                $(this).attr({"for": forVal});
            };
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newEl);
        let lastRow = $('.price-row:last > .buttons');

        // add remove button if it is the 2nd form
        if (!lastRow.has('.remove-form-row').length){
            lastRow.append('<div class="col-6">\
                                <button type="button" class="btn btn-block btn-outline-danger remove-form-row">\
                                <i class="fas fa-minus"></i></button>\
                            </div>');
        }
        if (!lastRow.has('.add-form-row').length)
            lastRow.find('div:first').append('<button type="button" \
                                                        class="btn btn-block btn-primary add-form-row">\
                                                        <i class="fas fa-plus"></i></button>');
        //adds remove button to first
        let firstRow = $('.price-row:first > .buttons');
        if (!firstRow.has('.remove-form-row').length)
            firstRow.append('<div class="col-6">\
                                <button type="button" class="btn btn-block btn-outline-danger remove-form-row">\
                                <i class="fas fa-minus"></i></button>\
                            </div>');
        let conditionRow = $('.price-row:not(:last)');
        conditionRow.find('.btn.add-form-row').remove()

        return false;
    }

    function deleteForm(prefix, btn) {
        let total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total >1) {
            let forms = "";
            let id_form = btn.closest('.price-row').find("input:first").attr('id').split('-')[1];
            if ( id_form < $('#id_' + prefix + '-INITIAL_FORMS').val() ){
                $("#id_prices-" + id_form + "-DELETE").prop('checked', true)
                btn.closest('.price-row').hide();
                forms = $('.price-row:visible');
            } else{
                btn.closest('.price-row').removeClass("price-row").remove()
                forms = $('.price-row');
                for( var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each( function() {
                        updateFieldIndex(this, prefix, i);
                    });
                };
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            }
            let lastRow = $('.price-row:visible:last > .buttons');
            if ($('.price-row:visible').length === 1) {
                $('.price-row:visible:last > .buttons > div:last').remove()
            }
            if (!lastRow.has('.add-form-row').length)
            lastRow.find('div:first').append('<button type="button" \
                                                        class="btn btn-block btn-primary add-form-row">\
                                                        <i class="fas fa-plus"></i></button>');
        }
    }
    $(document).on('click', '.add-form-row', function(e){
        e.preventDefault();
        addMore('.price-row:last', 'prices');
        return false;
    });
    $(document).on('click', '.remove-form-row', function(e){
        e.preventDefault();
        deleteForm('prices', $(this));
        return false;
    });
    $(document).on('change', '#id_photo', function(e) {
        let fileName = e.target.files[0].name;
         $('label[for="'+$('#id_photo').attr('id')+ '"]').text(fileName)
    });

    // Add events for currency conversion
	$("#idPrices").find(':input[type=text]').each( function () {
		$(this).on( 'blur', onBlur);
		$(this).on( 'focus', onFocus);
		$(this).on( 'mouseover', onMouseOver);
		$(this).on( 'mouseout', onMouseOut);
	});

	// string to currency conversion functions
    var currency = 'USD';
    function localStringToNumber( s ){
        return Number(String(s).replace(/[^0-9.-]+/g,""));
    }

    function onMouseOver(e){
      $(this).attr("pattern", "[0-9]*");
    }

    function onMouseOut(e){
      if(!$(this).is(":focus")) this.removeAttribute("pattern");
    }

    function onFocus(e){
      var intFormat= e.target.value;
      $(this).attr("pattern", "[0-9]*");
      var value = intFormat.replace(/[.]/g,',');
      e.target.value = value ? localStringToNumber(value) : '';
      $(this).prev().val(value);
    }

    var timeout = null
    function onBlur(e){
      	this.removeAttribute("pattern");
      	var value = e.target.value;
        $(this).prev().val(value);
        clearTimeout(timeout);
        timeout = setTimeout(function () {
			this.value = value;
            const options = {
				maximumFractionDigits : 0,
				minimumFractionDigits : 0,
				currency              : currency,
				style                 : "currency",
				currencyDisplay       : "symbol",
			}
            var usformat = value ? localStringToNumber(value).toLocaleString(undefined, options): '';
            val = usformat.replace(/[,]/g,'.');
            e.target.value = val.replace(/[US]/g,'');
            this.value = e.target.value;
      	}, 200);
    }

    $('#id_prices-TOTAL_FORMS').val($('#id_prices-INITIAL_FORMS').val() == 0 ? 1 : $('#id_prices-INITIAL_FORMS').val() )
});
</script>
{% endblock %}

menus/templates/chunks/select_product.html
<div class="row text-center mx-1 mt-1">
    <select id="productOptions" class="form-control col-12 col-md-6 offset-md-3">
        {% for key, values in products.items %}
            {%if values|length > 1 %}
                {% for value in values %}
                    {% if forloop.counter == 1 %}
                        <option value="{{key}}">{{value}}...</option>
                    {% else %}
                        <option  disabled style="font-style:italic">&nbsp;&nbsp;&nbsp;...{{value}}</option>
                    {% endif %}
                {% endfor %}
            {% else %}
                <option  value="{{key}}">{{values.0}}</option>
            {% endif %}
        {% endfor %}
    </select>
</div>
<input value="{{id}}" id="itemId" style="display:none;">