cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('liq/checkout', views.cart_detail_liqour, name='cart_detail_liq'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delivery/', views.DeliveryDetails.as_view(), name='cart_delivery'),
    path('liq/delivery/', views.DeliveryDetailsLiqour.as_view(), name='cart_delivery_liq'),
]

menus/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path('test/', views.ViewTest.as_view(), name='test'),
    path('upload_menu/', views.menu_upload, name='upload'),
    path('upload_size/', views.size_upload, name='upload-size'),
    path('upload_add_ons/', views.add_ons_upload, name='upload-add_ons'),
    path('price/<int:item_id>', views.item_prices_get, name='price'),
    path('adds_on/<int:item_id>', views.get_adds_on, name='adds-on'),
    path('same_item/<int:item_id>', views.same_items_in_cart, name='same-item'),
    path('order/<int:item_id>', views.item_to_order, name='order'),
    path('list/<str:city>/', views.MenuList.as_view(), name='list'),
    path('create/', views.MenuCreate.as_view(), name='create'),
    path('item_create/', views.ItemCreate.as_view(), name='item-create'),
    path('item_update/<int:pk>', views.ItemUpdate.as_view(), name='item-update'),
    path('item_delete/<int:pk>', views.ItemDelete.as_view(), name='item-delete'),
    path('get_category_items/<int:cat_id>', views.get_category_items, name='get-items'),
    path('category_create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category_update/<int:pk>', views.CategoryUpdate.as_view(), name='category-update'),
    path('category_delete/<int:pk>', views.CategoryDelete.as_view(), name='category-delete'),
    path('ad_update/<int:pk>', views.AdUpdate.as_view(), name='ad-update'),
    path('count_visit/', views.menu_access_count, name='count'),
    path('establishment_create/', views.EstablishmentCreate.as_view(), name='establishment-create'),
    path('<slug:title_slug>/editar/', views.MenuEditDetails.as_view(), name='edit'),
    path('<slug:title_slug>/edit/<int:partial>', views.MenuEditDetails.as_view(), name='edit-partial'),
    path('<slug:title_slug>/', views.MenuDetails.as_view(), name='details'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('', include('index.urls', namespace="index")),
    path('account/', include('account.urls', namespace='account')),
    path('menu/', include('menus.urls', namespace='menu')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext

from menus.helpers.functions import to_currency

CHOICES_TIP = [(i, to_currency(i)) for i in range(0, 20000, 1000)]
CHOICES_TIP_PERCENT = [(i, str(i) + "%") for i in range(0, 25, 5)]


class DetailsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = _('opcional')
        self.fields['address'].widget.attrs['placeholder'] = _('*requerida')
        self.fields['comments'].widget.attrs['placeholder'] = _('opcional')
        self.fields['name'].widget.attrs['class'] = "form-control"
        self.fields['address'].widget.attrs['class'] = "form-control"
        self.fields['comments'].widget.attrs['class'] = "form-control"
        self.fields['tip'].widget.attrs['class'] = "form-control"
        self.fields['tip_percent'].widget.attrs['class'] = "form-control"

    name = forms.CharField(max_length=40, required=False, label=_('name'))
    address = forms.CharField(max_length=90, required=True, label=_('address or table'), )
    comments = forms.CharField(max_length=90, required=False, label=_('comments'))
    pickup = forms.ChoiceField(choices={('RECOGE', _('Restaurant')),
                                        ('DOMICILIO', _('delivery'))},
                               label=_('Delivery'),
                               widget=forms.RadioSelect)
    tip = forms.CharField(max_length=7, required=False, initial="$0")
    tip_percent = forms.ChoiceField(choices=CHOICES_TIP_PERCENT, label=_('tip'), required=False)
    tip_number = forms.CharField(max_length=7, widget=forms.HiddenInput, initial=0)

menus/views.py
import csv
import io
import unidecode
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, TemplateView, DetailView, UpdateView, DeleteView

from cart.cart import Cart
from menus.forms import MenuForm, CategoryForm, EstablishmentForm, ItemForm, ItemPriceFormSet, MenuUploadForm, \
    SizeUploadForm, ItemPriceFormSet2, AdForm
from menus.models import Menu, Item, Category, Establishment, Price, AddsOn, ProductInCart, Quantity, MenuAnalytic, \
    MenuAdvertising
from django.utils.translation import gettext_lazy as _


class MenuCreate(CreateView):
    """View to create menu"""
    model = Menu
    form_class = MenuForm
    template_name = "menus/create.html"
    success_url = reverse_lazy('menu:item-create')


class MenuList(ListView):
    """View for displaying all menus"""
    model = Menu
    template_name = "menus/list.html"
    paginate_by = 2

    def get_queryset(self):
        qs = super().get_queryset()
        city = self.kwargs['city']
        category = self.request.GET.get('category')
        if city:
            capitalized_city = city.capitalize()
            unaccented_city = unidecode.unidecode(city)
            city_list = [city, capitalized_city, unaccented_city]
            if category:
                return qs.filter(city__in=city_list, establishment=category)
            return qs.filter(city__in=city_list)
        return qs


class ItemCreate(CreateView):
    """View to create Item"""
    model = Item
    form_class = ItemForm
    template_name = "chunks/item_crud.html"
    success_url = reverse_lazy('menu:item-create')

    def get(self, request, *args, **kwargs):
        try:
            self.category = Category.objects.get(id=request.GET['category_id'])
        except:
            self.category = ""
        try:
            self.menu = Menu.objects.get(id=request.GET['menu_id'])
        except:
            self.menu = ""
        return super(ItemCreate, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            self.category = Category.objects.get(id=request.POST['category_id'])
        except:
            self.category = ""
        try:
            self.menu = Menu.objects.get(id=request.POST['menu_id'])
        except:
            self.menu = ""
        return super(ItemCreate, self).post(self, request, *args, **kwargs)

    def form_valid(self, form):
        """valid the other 2 forms, location and property details"""
        context = self.get_context_data()
        prices = context['price']
        if prices.is_valid():
            item = form.save()
            prices.instance = item
            prices.save()
            return render(self.request, 'chunks/item_display.html', {'item': item,
                                                                     'list': [0, item.category.id],
                                                                     'edit': False})
        return super(ItemCreate, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        """Add price inline form"""
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['price'] = ItemPriceFormSet(self.request.POST)
            context['cat_id'] = self.category.id
        else:
            context['price'] = ItemPriceFormSet()
            context['cat_id'] = self.category.id

        return context

    def get_form_kwargs(self):
        kwargs = super(ItemCreate, self).get_form_kwargs()
        kwargs['owner'] = self.menu.owner
        kwargs['menu'] = self.menu
        kwargs['category'] = self.category
        return kwargs


class ItemUpdate(UpdateView):
    """View to create Item"""
    model = Item
    form_class = ItemForm
    template_name = "chunks/item_crud.html"
    success_url = reverse_lazy('menu:upload')

    def get(self, request, *args, **kwargs):
        try:
            self.category = Category.objects.get(id=request.GET['category_id'])
        except:
            self.category = ""
        try:
            self.menu = Menu.objects.get(id=request.GET['menu_id'])
        except:
            self.menu = ""
        return super(ItemUpdate, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            self.category = Category.objects.get(id=request.POST['category_id'])
        except:
            self.category = ""
        try:
            self.menu = Menu.objects.get(id=request.POST['menu_id'])
        except:
            self.menu = ""
        return super(ItemUpdate, self).post(self, request, *args, **kwargs)

    def form_valid(self, form):
        """valid the other 2 forms, location and property details"""
        context = self.get_context_data()
        prices_form = context['price']
        if prices_form.is_valid():
            item = form.save()
            prices_form.save()
            return render(self.request, 'chunks/item_display.html', {'item': item,
                                                                     'list': [0, item.category.id],
                                                                     'edit': True})
        return super(ItemUpdate, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        """Add price inline form"""
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['price'] = ItemPriceFormSet2(self.request.POST, instance=self.object)
            context['cat_id'] = self.category.id
            context['item_id'] = self.object.id
        else:
            context['price'] = ItemPriceFormSet2(instance=self.object)
            context['cat_id'] = self.category.id
            context['item_id'] = self.object.id

        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdate, self).get_form_kwargs()
        kwargs['owner'] = self.menu.owner
        kwargs['menu'] = self.menu
        kwargs['category'] = self.category
        return kwargs


class ItemDelete(DeleteView):
    model = Item

    def delete(self, request, *args, **kwargs):
        item = self.get_object()
        item_id = item.id
        item.delete()
        if Category.objects.filter(id=item_id).exists():
            return JsonResponse({'msg': 'error. por favor intentelo de nuevo'})
        else:
            divId = '#div-item' + str(item_id)
            return JsonResponse({'id': divId})


class CategoryCreate(CreateView):
    """View to create Category"""
    model = Category
    form_class = CategoryForm
    template_name = "chunks/category_crud.html"
    success_url = reverse_lazy('menu:edit')

    def post(self, request, *args, **kwargs):
        self.menu = Menu.objects.get(id=request.POST['menu_id'])
        self.owner = get_user_model().objects.get(id=request.POST['menu_owner'])
        return super(CategoryCreate, self).post(self, request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.menu.owner
        self.object.menu = self.menu
        self.object.save()
        return redirect(reverse('menu:edit-partial', kwargs={'title_slug': self.menu.title_slug, 'partial': 1}))


class CategoryUpdate(UpdateView):
    """View to create Category"""
    model = Category
    form_class = CategoryForm
    template_name = "chunks/category_crud.html"

    def post(self, request, *args, **kwargs):
        self.menu = Menu.objects.get(id=request.POST['menu_id'])
        return super(CategoryUpdate, self).post(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """pass id to template"""
        context = super().get_context_data(**kwargs)
        context['id'] = self.object.id
        return context

    def form_valid(self, form):
        position = Category.objects.get(id=self.object.id).position
        if position != form.cleaned_data['position']:
            self.object = form.save()
            return redirect(reverse('menu:edit-partial', kwargs={'title_slug': self.menu.title_slug, 'partial': 1}))
        self.object = form.save()
        divId = '#cat' + str(self.object.id)
        return JsonResponse({'id': divId, 'name': self.object.name})


class CategoryDelete(DeleteView):
    model = Category

    def delete(self, request, *args, **kwargs):
        category = self.get_object()
        cat_id = category.id
        # cat_name = category.name
        category.delete()
        if Category.objects.filter(id=cat_id).exists():
            return JsonResponse({'msg': 'error. por favor intentelo de nuevo'})
        else:
            divId = '.cat-' + str(cat_id)
            return JsonResponse({'id': divId})


class EstablishmentCreate(CreateView):
    """View to create Establishment"""
    model = Establishment
    form_class = EstablishmentForm
    template_name = "chunks/Establishment_create.html"


class ViewTest(TemplateView):
    template_name = "menus/details3.html"


class MenuDetails(DetailView):
    """View Menu with items"""
    model = Menu
    template_name = "menus/details.html"
    slug_url_kwarg = 'title_slug'
    slug_field = 'title_slug'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        cart = Cart(request)
        print(cart)
        for item in cart:
            try:
                menu = item['product'].price.item.menu
                if menu != self.get_object():
                    keys = request.session['cart'].keys()
                    for item in ProductInCart.objects.filter(id__in=keys):
                        item.delete()

menus/templates/menus/apetitet.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load menu_tags %}
{% block title %}
{% trans 'Menu' %}
{% endblock %}

{% block styles %}
<link href="https://fonts.googleapis.com/css2?family=Germania+One&display=swap" rel="stylesheet">

<style>
    /* For Firefox */
    input[type='number'] {
        -moz-appearance:textfield;
    }

    .itemQty > .form-control:disabled, itemQty > .form-control[readonly]{
        background-color: #fff;
        border: solid 1px #000;
        font-size: 1.2rem;
        color: #000;
    }

    /* Webkit browsers like Safari and Chrome */
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    hr {
        background-color: #a0705e !important;
    }

    .card-header > button{
        font-family: 'Germania One', cursive;
        font-size: 2rem !important;
        color: #3c2316 !important;
    }

    .input-group-prepend > button, .input-group-append > button{
        border: solid 1px #613924;
        //background-color: #be7650;
        background-image: linear-gradient(#e5bd3b, #e5bd3b);
        color: white;
    }
    .addButton > button{
        border: solid 1px #613924;
        background-image: linear-gradient(#e5bd3b, #e5bd3b);
        font-family: 'Germania One', cursive;
        color: white;
    }

    .input-group-prepend > button:hover, .input-group-append > button:hover{
        color: #000;
    }
    .addButton > button:hover{
        color: #000;
    }
    .card-header{
        background-image: linear-gradient(#e5bd3b, #dbb331);
        text-transform: uppercase;
    }

    .card-body{
        background-color: #FFFFFF;
    }

    .dish{
        color: #000;
    }
    .ingredients{
        color: #000;
    }
    .dish > span{
        position: relative;
        top: -5px !important;
    }

    .dropBut {
        font-size: 1.3rem;
        right: 30px;
        position: relative;
        top: -7px;
    }

   .info {
        background-image: linear-gradient(#e5bd3b, #9f7700);
        color: #ffffff;
        font-weight: 800;
    }
    .info > p > a {
        color:white !important;
    }
    .main{
        border-top: 1px solid #513122;
    }
</style>
{% endblock %}

{% block body %}
<div class="d-flex flex-row justify-content-between align-items-center bg-light p-1 rounded my-1">
    <div class="px-1">
        {% if menu.logo.url%}
            <img src="{{menu.logo.url}}" class="img-fluid rounded" height="300" width="300">
        {% endif%}
    </div>
    <div class="p-1 p-sm-2 p-md-3 rounded info">
        <h6>Contactanos:</h6>
        <p><i class="fa fa-phone-square mt-2">&nbsp;</i> <a href="tel:+573126167907"> 312-616-7907(llamar)</a></p>
        <p class="my-1"><i class="fa fa-map-marker">&nbsp;</i><a href="{{map_url}}" target="_blank"> Cra 11 # 20A - 25 (ver en google maps)</a></p>
        {% if map_url2 %}
            <p class="my-0"><a href="{{map_url2}}" target="_blank">(ver en apple maps)</a></p>
        {% endif %}
    </div>
</div>
<div class="row main pt-2">
    <div class="accordion col-12 col-md-6 px-1" id="accordionMenu">
        {% for category, id in items.items %}
            <div class="card">
                <div class="card-header p-1" id="heading{{id}}">
                    <button class="btn btn-link btn-block text-center px-1" type="button" data-toggle="collapse" data-target="#cat{{id}}" aria-expanded="true" aria-controls="cat{{id}}">
                        {{category}} <span class="float-right"><span class="float-right dropBut"><small>&nbsp;abrir&nbsp;</small></span><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                    </button>
                </div>
                <div id="cat{{id}}" class="collapse shadow" aria-labelledby="heading{{id}}" data-parent="#accordionMenu">
                    <div class="text-center my-2">
                      <div class="spinner-grow text-secondary" role="status">
                        <span class="sr-only">Loading...</span>
                      </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-12 col-md-6 px-1" id="divAd">
        {% include "chunks/carousel_ads.html" %}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(".collapse").each(function (){
        $(this).on('shown.bs.collapse', function () {
            let title = $(this).prev().find("button").find("span").last();
            let icon = $(this).prev().find("button").find("i");
            icon.removeClass("fa-caret-down");
            icon.addClass("fa-caret-up");
            title.html("<small>cerrar</small>");
            $('html,body').animate({
                scrollTop: $(this).offset().top-80
            }, 'slow');
        })
        $(this).on('show.bs.collapse', function () {
            let divId = $(this).attr("id");
            let id = divId.replace("cat", "");
            if ($(this).find('.card-body').length < 1){
                loadItems(parseInt(id));
            }
            let title = $(this).prev().find("button").find("span").last();
            let icon = $(this).prev().find("button").find("i");
            icon.removeClass("fa-caret-down");
            icon.addClass("fa-caret-up");
            title.html("<small>cerrar</small>");
        })
         $(this).on('hide.bs.collapse', function () {
            let title = $(this).prev().find("button").find("span").last();
            let icon = $(this).prev().find("button").find("i");
            icon.removeClass("fa-caret-up");
            icon.addClass("fa-caret-down")
            title.html("<small>&nbsp;abrir&nbsp;</small>");
        })
    })
    $('.carousel').carousel({
      interval: 2500
    })
    function loadItems(id){
        let items;
        $.ajax({
            type: 'get',
            url: "{% url 'menu:get-items' 123 %}".replace( /123/, id),
            success: function(data){
                let div = document.getElementById("cat" + id);
                div.innerHTML = data;
                checkQty();
            }
        });
        return items;
    }
    function checkQty (){
        $(".addRemoveButtons :input[type=number]").each( function () {
            if ($(this).val() < 1){
               $(this).parent().next().show();
               $(this).parent().hide();
               $(this).parent().parent().parent().find('span').hide();
            } else {
               $(this).parent().next().hide();
               $(this).parent().show();
               $(this).parent().parent().parent().find('span').show();

            }
        });
    }
        $(document).on('change', '#id_tip_percent', function(e){
        bindInputsItem()
        let total = $("#totalOrder").val();
        tip = total / 10000 * $("#id_tip_percent").val();
        tip_rounded = tip.toFixed(0);
        tip_fix = tip_rounded * 100
        $("#id_tip").val(tip_fix);
        $("#id_tip").trigger('blur');
    })

    // Add events for currency conversion
    function bindInputsItem(){
         $("#id_tip").on( 'blur', onBlur);
         $("#id_tip").on( 'focus', onFocus);
         $("#id_tip").on( 'mouseover', onMouseOver);
         $("#id_tip").on( 'mouseout', onMouseOut);
    }

	// string to currency conversion functions
    var currency = 'USD';
    function localStringToNumber( s ){
        return Number(String(s).replace(/[^0-9.-]+/g,""));
    }

    function onMouseOver(e){
      $(this).attr("pattern", "[0-9]*");
    }

    function onMouseOut(e){
      if(!$(this).is(":focus")) this.removeAttribute("pattern");
    }

    function onFocus(e){
      var intFormat= e.target.value;
      $(this).attr("pattern", "[0-9]*");
      var value = intFormat.replace(/[.]/g,',');
      e.target.value = value ? localStringToNumber(value) : '';
      $(this).prev().val(value);
    }

    var timeout = null
    function onBlur(e){
      	this.removeAttribute("pattern");
      	var value = e.target.value;
      	$(this).prev().val(value);
        clearTimeout(timeout);
        timeout = setTimeout(function () {
			this.value = value;
            const options = {
				maximumFractionDigits : 0,
				minimumFractionDigits : 0,
				currency              : currency,
				style                 : "currency",
				currencyDisplay       : "symbol",
			}
            var usformat = value ? localStringToNumber(value).toLocaleString(undefined, options): '';
            val = usformat.replace(/[,]/g,'.');
            e.target.value = val.replace(/[US]/g,'');
            this.value = e.target.value;
      	}, 200);
    }
</script>
{% endblock %}

menus/templates/menus/create.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Menu' %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
<form  method="post">{% csrf_token %}
    <div class="row">
        <div class="col-7">
                <div>
                    {{form.owner.label}}
                    {{form.owner}}
                </div>
                <div>
                    {{form.establishment.label}}
                    {{form.establishment}}
                </div>
                <div>
                    {{form.title.label}}
                    {{form.title}}
                </div>
                <div>
                    {{form.subtitle.label}}
                    {{form.subtitle}}
                </div>
                <div>
                    {{form.description.label}}
                    {{form.description}}
                </div>
        </div>
        <div class="col-5">
            <div>
                {{form.logo.label}}
                {{form.logo}}
            </div>
        </div>
    </div>
    <hr>
    <div class="row mb-2">
        <div class="col-8 offset-2">
        <button class="btn btn-block btn-primary" type="submit">{% trans 'SAVE' %}</button>
        </div>
    </div>
</form>
{% endblock %}

{% block scripts %}
{% endblock %}

menus/templates/menus/list.html
{% load i18n %}
{% load static %}
    <hr>
    <div class="row" >
        <p class="lead" id="titleResult">{% trans 'Restaurants'%} {% trans 'of' %} <strong>category</strong>  {% trans 'in' %} city  </p>
    </div>
    <div class="row">
        {% for menu in object_list %}
        <div class="col-12 col-md-6 mt-3 px-4 h-100 ">
        <div class="row border bg-light ">
                <div class="col-12 px-0 position-absolute d-flex justify-content-end" style="right:0px; top:-5px; z-index:100;">
                    <span class="badge badge-pill badge-secondary">{{menu.city}}</span>
                </div>
                <div class="col-3 col-lg-3 px-0">
                    <img class="img-fluid" src="{{menu.logo.url}}" alt="Card image cap">
                <div class="col-12 px-0 position-absolute d-flex justify-content-start" style="bottom:2px; left:2px; z-index:100;">
                    <span class="badge badge-primary"><small>{{menu.establishment}}</small></span>
                </div>
                </div>
                <div class="col-9 col-lg-6 px-0">
<!--                    <div class="col-12 bg-primary px-0 border-bottom position-absolute d-flex justify-content-between">-->
<!--                         <p class="text-white mb-0 px-3">{{menu.establishment}}</p>-->
<!--                    </div>-->
                    <div class="col-12 pl-0 pr-2 pt-2">
                        <h4 class="card-title text-primary my-0 pl-3">{{menu.title}}</h4>
                        <p class="text-primary my-0 pl-3"><small>{{menu.subtitle}}</small></p>
                        <a class="text-primary pl-3 my-0" href="https://maps.google.com/?q={{menu.lat}}, {{menu.lng}} ">
                            {% trans 'Address' %}: <u>{{menu.address}} <i class="fa fa-map-marker" aria-hidden="true"></i> </u>
                        </a>
                        <p class="text-primary pl-3 my-0">{% trans 'Phone' %} {{menu.owner.profile.phone}}</p>
                    </div>
                </div>
                <div class="row col-12 col-lg-3 mb-1 mt-md-4 pr-0 px-md-1">
                    <div class="col-4 col-lg-12 px-1 pt-1 text-center">
                        <a href="{{whatsapp_url}}" type="button" class="btn btn-sm btn-block btn-success">
                                <i class="fab fa-whatsapp"></i> Whatsapp
                        </a>
                    </div>
                    <div class="col-4 col-lg-12 px-1 pt-1 text-center">
                        <a href="{% url 'menu:details' menu.title_slug %}" class="btn btn-sm btn-block btn-primary">{% trans 'See Menu'%}</a>
                    </div>
                    <div class="col-4 col-lg-12 px-1 pt-1 text-center">
                        <a type="button" class="btn btn-block btn-sm btn-outline-secondary" title="ver en google maps" data-toggle="modal" data-target="#Modal{{menu.id}}">
                            {% trans 'Hours' %}
                        </a>
                    </div>
                </div>
            </div>
        </div>



        <div class="modal fade" id="Modal{{menu.id}}" tabindex="-1"
             role="dialog" aria-labelledby="ModalMenu{{menu.id}}" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header bg-secondary">
                  <h5 class="modal-title"><strong>{{menu.title}}</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                {{menu.description}}
              </div>
              <div class="modal-footer p-1">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
    <hr>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm btn-primary">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm btn-primary">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}