cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('liq/checkout', views.cart_detail_liqour, name='cart_detail_liq'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delivery/', views.DeliveryDetails.as_view(), name='cart_delivery'),
    path('liq/delivery/', views.DeliveryDetailsLiqour.as_view(), name='cart_delivery_liq'),
]

menus/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path('test/', views.ViewTest.as_view(), name='test'),
    path('upload_menu/', views.menu_upload, name='upload'),
    path('upload_size/', views.size_upload, name='upload-size'),
    path('upload_add_ons/', views.add_ons_upload, name='upload-add_ons'),
    path('price/<int:item_id>', views.item_prices_get, name='price'),
    path('adds_on/<int:item_id>', views.get_adds_on, name='adds-on'),
    path('same_item/<int:item_id>', views.same_items_in_cart, name='same-item'),
    path('order/<int:item_id>', views.item_to_order, name='order'),
    path('list/<str:city>/', views.MenuList.as_view(), name='list'),
    path('create/', views.MenuCreate.as_view(), name='create'),
    path('item_create/', views.ItemCreate.as_view(), name='item-create'),
    path('item_update/<int:pk>', views.ItemUpdate.as_view(), name='item-update'),
    path('item_delete/<int:pk>', views.ItemDelete.as_view(), name='item-delete'),
    path('get_category_items/<int:cat_id>', views.get_category_items, name='get-items'),
    path('category_create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category_update/<int:pk>', views.CategoryUpdate.as_view(), name='category-update'),
    path('category_delete/<int:pk>', views.CategoryDelete.as_view(), name='category-delete'),
    path('ad_update/<int:pk>', views.AdUpdate.as_view(), name='ad-update'),
    path('count_visit/', views.menu_access_count, name='count'),
    path('establishment_create/', views.EstablishmentCreate.as_view(), name='establishment-create'),
    path('<slug:title_slug>/editar/', views.MenuEditDetails.as_view(), name='edit'),
    path('<slug:title_slug>/edit/<int:partial>', views.MenuEditDetails.as_view(), name='edit-partial'),
    path('<slug:title_slug>/', views.MenuDetails.as_view(), name='details'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('', include('index.urls', namespace="index")),
    path('account/', include('account.urls', namespace='account')),
    path('menu/', include('menus.urls', namespace='menu')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/forms.py
from django import forms

from menus.models import Establishment


class SearchBarForm(forms.Form):
    """Index main search bar form inputs"""
    city = forms.CharField(max_length=127, required=False)
    establishments = forms.ModelChoiceField(queryset=Establishment.objects.all(), empty_label="Todas las categorias")

index/templates/index/home.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Home' %}
{% endblock %}

{% block styles %}
{% endblock %}
{% block body %}
<div class="row text-primary mt-2">
    <div class="col-12 text-center">
        <h2 class="text-center"><i class="fas fa-angle-double-right"></i> La alternativa de menús 100% digital para tu negocio <i class="fas fa-angle-double-left"></i></h2>
    </div>
</div>
<hr>
<div class="row px-3">
    <div class="offset-1 col-10 px-0 col-md-4 offset-md-0 my-2 px-md-2 px-lg-3">
        <a data-toggle="collapse" href="#collapseFirst" role="button" class="bg-dark">
            <div class="card p-1 bg-light border-secondary shadow-sm" id="firstCard">
                <span class=" position-absolute lead font-weight-bolder text-primary float-left p-2">¿Quiénes somos?</span>
                <img src="{% static 'images/default/logo.png' %}" class="card-img-top" alt="...">
            </div>
        </a>
    </div>
    <div class="offset-1 col-10 px-0 col-md-4 offset-md-0 my-2 px-md-2 px-lg-3" id="secondCard">
        <a data-toggle="collapse" href="#collapseSecond" role="button">
            <div class="card p-1 bg-light border-secondary shadow-sm">
                <span class=" position-absolute lead font-weight-bolder text-primary float-left p-2">¿Cómo funciona?</span>
                <img src="{% static 'images/default/phone.png' %}" class="card-img-top" alt="...">
            </div>
        </a>
    </div>
    <div class="offset-1 col-10 px-0 col-md-4 offset-md-0 my-2 px-md-2 px-lg-3" id="thirdCard">
        <a data-toggle="collapse" href="#collapseThird" role="button" class="disabled">
            <div class="card p-1 bg-light border-secondary shadow-sm">
                <span class=" position-absolute lead font-weight-bolder text-primary float-left p-2">Beneficios de Digimenú</span>
                <img src="{% static 'images/default/stars.png' %}" class="card-img-top" alt="...">
            </div>
        </a>
    </div>
</div>
<div class="row collapse m-2" id="collapseFirst">
      <div class="col-12 col-md-4 bg-primary text-white text-center rounded-left p-3">
          <h3>¿Quiénes somos?</h3>
      </div>
      <div class="col-12 col-md-8 bg-secondary rounded-right p-3 lead">
        Somos la alternativa de menús 100% digitales que facilitan la venta de tus productos de forma remota, mejorando la experiencia de tus clientes y tu servicio hacia ellos.
      </div>
</div>
<div class="row collapse m-2" id="collapseSecond">
      <div class="col-12 col-md-4 bg-primary text-white text-center rounded-left p-3">
          <h3>¿Cómo funciona?</h3>
          ¡Ten Digimenú Colombia en 5 pasos!
      </div>
      <div class="col-12 col-md-8 bg-secondary rounded-right p-3 lead">
          <ol>
              <li>Selecciona el tamaño de tu menú: Mini, súper o maxi</li>
              <li>Envíanos la información de tu menú</li>
              <li>Recibe la propuesta de tu Digimenú y apruébala</li>
              <li>Recibe tu link y código QR personalizado</li>
              <li>Empieza a promover tus productos de una forma  100% digital y remota</li>
          </ol>
      </div>
</div>
<div class="row collapse m-2" id="collapseThird">
      <div class="col-12 col-md-4 bg-primary text-white text-center rounded-left p-3">
          <h3>Beneficios de Digimenú</h3>
          ¿Cómo beneficia a mi negocio?
      </div>
      <div class="col-12 col-md-8 bg-secondary rounded-right p-3 lead">
          <ul>
              <li>Promueve la gestión digital de tu negocio</li>
              <li>Facilita el proceso de compra a tus clientes</li>
              <li>Reduce los tiempos de respuesta a tus clientes</li>
              <li>Mejora la imagen de tu negocio</li>
              <li>Reduce la transmisión de bacterias con menús físicos</li>
          </ul>
      </div>
</div>
{% endblock %}

{% block scripts %}
<script>
$("#collapseFirst").on('show.bs.collapse', function () {
    $("#collapseSecond").collapse('hide');
    $("#collapseThird").collapse('hide');
});
$("#collapseFirst").on('shown.bs.collapse', function () {
    $('html,body').animate({
        scrollTop: $('#collapseFirst').offset().top
    }, 'slow');
});
$("#collapseSecond").on('show.bs.collapse', function () {
    $("#collapseFirst").collapse('hide');
    $("#collapseThird").collapse('hide');
});
$("#collapseSecond").on('shown.bs.collapse', function () {
    $('html,body').animate({
        scrollTop: $('#collapseSecond').offset().top
    }, 'slow');
});
$("#collapseThird").on('show.bs.collapse', function () {
    $("#collapseFirst").collapse('hide');
    $("#collapseSecond").collapse('hide');
});
$("#collapseThird").on('shown.bs.collapse', function () {
    $('html,body').animate({
        scrollTop: $('#collapseThird').offset().top
    }, 'slow');
});
</script>
{% endblock %}

index/templates/index/index.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Home' %}
{% endblock %}

{% block styles %}
<!--    INDEX STYLE-->
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
{% endblock %}
{% block body %}
<div hidden>    <!--    hidden input for form-->
    <form id="searchForm" method="post">{% csrf_token %}
        {{form.city}}
        {{form.establishments}}
    </form>
</div>
<div class="text-center">
    <h1 class="display-4 text-primary"><em>"Aqui encuentras los mejores restauranteas de tu ciudad"</em></h1>
    <h3 class="text-secondary">De que te antojas hoy?</h3>
</div>
<div class="input-group col-lg-12  col-xl-10 offset-xl-1  col-md-12  col-sm-12 my-5">
    <div class="col-xm-12 col-sm-4 col-lg-4 mx-0 px-0">
        <button id="butEstablishment" class="btn btn-outline-primary btn-lg btn-block dropdown-toggle down-in-group1" type="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{form.establishments}}
        </button>
        <div class="dropdown-menu col-sm-12 text-center">
            {% for choice in form.establishments.field.choices%}
            <a class="dropdown-item" onclick="selectEstablishment('{{choice.0}}')">{{choice.1}}</a>
            {% endfor %}
        </div>
    </div>
<!--    <div class="col-xm-12 col-sm-4 col-lg-3 mx-0 px-0">-->
<!--        <button id="butProperty" class="btn btn-outline-secondary btn-lg  btn-block dropdown-toggle down-in-group2" type="button"-->
<!--                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Apartment' %}-->
<!--        </button>-->
<!--        <div class="dropdown-menu col-sm-12 text-center">-->
<!--            {% for choice in form.property_type.field.choices%}-->
<!--            <a class="dropdown-item" onclick="selectPropertyType('{{choice.0}}')">{{choice.1}}</a>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="col-xs-12 col-sm-4 col-lg-2  mx-0 px-0">-->
<!--        <button id="butCondition" class="btn btn-outline-secondary btn-lg btn-block dropdown-toggle down-in-group3"  type="button"-->
<!--                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'New' %}-->
<!--        </button>-->
<!--        <div class="dropdown-menu col-sm-12 text-center">-->
<!--            {% for choice in form.property_condition.field.choices%}-->
<!--            <a class="dropdown-item" onclick="selectCondition('{{choice.0}}')">{{choice.1}}</a>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->
    <input type="text" class="form-control input-in-group form-control-lg px-2" id="autocomplete"  placeholder=" Busca tu ciudad"
           aria-label="input with three button addons"  aria-describedby="button-addon3">
    <div class="input-group-append">
        <button id="submitButton" type="button" class="btn btn-primary button-in-group"><i class="fas fa-search"></i></button>
    </div>
</div>
<div id="results" class="container"></div>
{% endblock %}
{% block scripts %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4Gol1U3BbHLkWzeJb5kbggvFAPVKZRAA&libraries=places&region=CO"></script>
<script>
    // submit hidden form
    $("#submitButton").click( function() {
        //$("#searchForm").submit();
        let city = $("#id_city").val();
        let category = $("#id_establishments").val();
        $.ajax({
            type: "get",
            url: "{% url 'menu:list' 123 %}".replace( '123', city),
            data: {category:category},
            success: function(data) {
                let resultDiv = document.getElementById('results');
                resultDiv.innerHTML = data;
                $("#titleResult").text($("#titleResult").text().replace('category' , $("#id_establishments option:selected").text().toUpperCase()));
                $("#titleResult").text($("#titleResult").text().replace('city' , $("#id_city").val().toUpperCase()));
                $('html, body').animate({
                        scrollTop: $('#results').offset().top
                }, 'fast');
            }
        });
    });
    $("#autocomplete").keyup( function() {
          $("#id_city").val($("#autocomplete").val());
    });

    function geoLocate() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(getPosition, noLocation);
      }
    }
    function noLocation(err){
        console.warn('ERROR(' + err.code + '): ' + err.message);
    }
    function getPosition(position){
        var lat = position.coords.latitude;
        var lon = position.coords.longitude;
        var latlng = {lat: parseFloat(lat), lng: parseFloat(lon)};
        geocoder.geocode({'location': latlng}, function(results, status) {
        if (status === 'OK') {
              if (results[0]) {
                alert(results[0].formatted_address);
              } else {
                window.alert('No results found');
              }
            } else {
              window.alert('Geocoder failed due to: ' + status);
            }
          });
    }

    function initAutocomplete() {
      // Create the autocomplete object, restricting the search predictions to
      // geographical location types.
      let addressIn = document.getElementById('autocomplete');
      autocomplete = new google.maps.places.Autocomplete(
        addressIn, {types: ['(cities)'], componentRestrictions: {country: 'co'}}
        //addressIn, {types: ['(cities)'], bounds: defaultBounds, strictBounds: true,}
      );

      // Avoid paying for data that you don't need by restricting the set of
      // place fields that are returned to just the address components.
        autocomplete.setFields(['address_components']);

      // When the user selects an address from the drop-down, populate the
      // address fields in the hidden form.
       autocomplete.addListener('place_changed', fillInAddress);
    }

    function fillInAddress() {
      // Get the place details from the autocomplete object.
      var place = autocomplete.getPlace();

      // fields to be populated
      //let locality = document.getElementById('id_locality');
      let city = document.getElementById('id_city');
      //let state = document.getElementById('id_state');

      for (var i = 0; i < place.address_components.length; i++) {
        var addressType = place.address_components[i].types[0];
        if (addressType === "administrative_area_level_2"){
            city.value = place.address_components[i].long_name;
            break;
         }
      }
    }

    function selectEstablishment(choice){
        $('#id_establishments option[value="' + choice +'"]').prop("selected", true);
        document.getElementById('butEstablishment').innerHTML = $('#id_establishments option:selected').html();
    };
    selectEstablishment()
    // start google maps autocomplete
    initAutocomplete()
    geoLocate()
</script>

{% endblock %}